# Generated by Django 3.2.10 on 2022-01-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='nombre')),
                ('user_lastname', models.CharField(max_length=30, verbose_name='apellido')),
                ('user_birthday', models.DateField(verbose_name='cumpleaños')),
                ('user_address', models.CharField(max_length=64, verbose_name='direccion')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=20, verbose_name='contraseña')),
                ('user_ocupation', models.CharField(max_length=40, verbose_name='ocupacion')),
                ('user_type', models.CharField(choices=[('1', 'client'), ('2', 'manager')], max_length=10, verbose_name='tipo')),
                ('is_active', models.BooleanField()),
                ('creat_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
