# Generated by Django 3.2.10 on 2022-01-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_date', models.DateField()),
                ('ord_state', models.CharField(choices=[('1', 'unconfirmed'), ('2', 'confirmed'), ('3', 'cancelled'), ('4', 'dispatched'), ('5', 'delivered')], max_length=30, verbose_name='estado')),
                ('ord_total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'OrdenProducto',
                'verbose_name_plural': 'OrdenesProductos',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='ord_product',
            field=models.ManyToManyField(blank=True, through='orders.OrderProduct', to='products.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
