# Generated by Django 3.2.10 on 2022-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_date', models.DateField()),
                ('not_title', models.CharField(max_length=100, verbose_name='Titulo_Notificacion')),
                ('not_body', models.CharField(max_length=100, verbose_name='cuerpo_notificacion')),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificaciones',
            },
        ),
    ]
