# Generated by Django 3.2.10 on 2022-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=30, verbose_name='nombre')),
                ('prod_count', models.IntegerField(blank=True, verbose_name='cantidad')),
                ('prod_description', models.CharField(max_length=200, verbose_name='descripcion')),
                ('prod_image_url', models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen')),
                ('prod_trademark', models.CharField(blank=True, max_length=30, verbose_name='marca')),
                ('prod_warranty', models.CharField(blank=True, max_length=10, verbose_name='garantia')),
                ('prod_tutorial_url', models.CharField(blank=True, max_length=30, null=True)),
                ('prod_creat_at', models.DateField(auto_now=True)),
                ('prod_is_active', models.BooleanField(verbose_name='activo')),
                ('prod_discount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
